# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true
plugins:
  [jekyll-paginate]

# Setup
title:               Fiona Voss
tagline:             'Software developer and computer science student'
description:         ''
url:                 http://fionavoss.github.io
baseurl:             ''
paginate:            1
related_posts:       false

# About/contact
author:
  name:              Fiona Voss

# Custom vars
version:             1.0.0
