---
title: Fiona Voss
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
plugins:
- jekyll-paginate
tagline: Software developer and computer science student
description: ''
url: http://fionavoss.github.io
baseurl: ''
paginate: 1
related_posts: false
twitter_username: fionajvoss
author:
  name: Fiona Voss
version: 1.0.0
